#include <math.h>
#include <shlwapi.h>
#include <stdio.h>

#include "clock.h"
#include "display.h"
#include "entity.h"
#include "game.h"
#include "input.h"
#include "mem_arena.h"
#include "platform.h"
#include "tile_map.h"
#include "win_common.h"

internal void SetExeDir( void );
internal void LoadWinDebugConfig( const char* filePath, u32* targetFps );
internal b32 CreateMainWindow( HINSTANCE hInstance );
internal LRESULT CALLBACK MainWindowProc( _In_ HWND hWnd, _In_ UINT uMsg, _In_ WPARAM wParam, _In_ LPARAM lParam );
internal void RenderScreen( void );
internal void InitButtonMap( void );
internal void HandleKeyboardInput( u32 keyCode, LPARAM flags );

WinDebugFlags_t g_winDebugFlags;
WinGlobalObjects_t g_winGlobals;

int CALLBACK WinMain( _In_ HINSTANCE hInstance, _In_opt_ HINSTANCE hPrevInstance, _In_ LPSTR lpCmdLine, _In_ int nCmdShow )
{
   TIMECAPS timeCaps;
   UINT timerResolution;
   RECT mainWindowRect;
   Display_t* display;
   char gameDataPath[MAX_PATH];
   u32 targetFps;

   UNUSED_PARAM( hPrevInstance );
   UNUSED_PARAM( lpCmdLine );
   UNUSED_PARAM( nCmdShow );

   SetExeDir();
   snprintf( g_winGlobals.logFilePath, MAX_PATH, "%s\\%s", g_winGlobals.exeDir, LOG_FILENAME );
   snprintf( gameDataPath, MAX_PATH, "%s\\%s", g_winGlobals.exeDir, GAME_DATA_FILENAME );
   snprintf( g_winGlobals.debugConfigPath, MAX_PATH, "%s\\%s", g_winGlobals.exeDir, WIN_DEBUG_CONFIG_FILENAME );

   Platform_Log( "----------------- LAUNCH -----------------" );

   g_winGlobals.memArena = MemArena_Create( GAME_MEMORY_SIZE );

   if ( !QueryPerformanceFrequency( &( g_winGlobals.performanceFrequency ) ) )
   {
      Platform_FatalError( "failed to query performance frequency." );
      MemArena_Free( g_winGlobals.memArena );
      return 1;
   }

   if ( timeGetDevCaps( &timeCaps, sizeof( TIMECAPS ) ) != TIMERR_NOERROR )
   {
      Platform_FatalError( "failed to set timer resolution." );
      MemArena_Free( g_winGlobals.memArena );
      return 1;
   }

   timerResolution = min( max( timeCaps.wPeriodMin, 1 ), timeCaps.wPeriodMax );
   timeBeginPeriod( timerResolution );

   Platform_Rand_Seed( (u32)Platform_GetMicros() );

   // TODO: this will eventually be generated by a game editor of some kind
   WriteTestGameDataFile( gameDataPath );

   g_winGlobals.graphicsScale = DEFAULT_GRAPHICS_SCALE;
   g_winDebugFlags.showDiagnostics = False;
   g_winGlobals.anchorDiagnosticsWindow = True;
   g_winDebugFlags.noClip = False;
   g_winDebugFlags.showHitBoxes = False;
   g_winDebugFlags.moveFast = False;
   targetFps = GAME_DEFAULT_FPS;
   LoadWinDebugConfig( g_winGlobals.debugConfigPath, &targetFps );

   g_winGlobals.buttonMap = (u32*)MemArena_AllocMem( g_winGlobals.memArena, sizeof( u32 ) * InputButton_Count );
   InitButtonMap();

   g_winGlobals.game = Game_Create( g_winGlobals.memArena, gameDataPath ); // does not transfer ownership of memory arena
   Clock_SetFps( Game_GetClock( g_winGlobals.game ), targetFps );

   if ( !CreateMainWindow( hInstance ) || !CreateDiagnosticsWindow( hInstance ) )
   {
      Platform_FatalError( "failed to create main or diagnostics window." );
      timeEndPeriod( timerResolution );
      MemArena_Free( g_winGlobals.memArena );
      return 1;
   }

   // move diagnostics out of the main window's way and give the main window focus
   if ( GetWindowRect( g_winGlobals.hWndMain, &mainWindowRect ) )
   {
      SetWindowPos( g_winGlobals.hWndDiagnostics,
                    HWND_TOP,
                    mainWindowRect.right + 16,
                    mainWindowRect.top,
                    0,
                    0,
                    SWP_NOSIZE );
      ShowWindow( g_winGlobals.hWndDiagnostics, g_winDebugFlags.showDiagnostics ? SW_SHOW : SW_HIDE );
      SetFocus( g_winGlobals.hWndMain );
   }

   SetCursor( LoadCursor( 0, IDC_ARROW ) );

   g_winGlobals.hFont = CreateFontA( 16, 0, 0, 0,
                                     FW_BOLD, FALSE, FALSE, FALSE,
                                     ANSI_CHARSET, OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS,
                                     DEFAULT_QUALITY, DEFAULT_PITCH | FF_SWISS,
                                     "Consolas" );

   display = Game_GetDisplay( g_winGlobals.game );
   g_winGlobals.bmpInfo.bmiHeader.biSize = sizeof( BITMAPINFOHEADER );
   g_winGlobals.bmpInfo.bmiHeader.biWidth = Display_GetWidth( display );
   g_winGlobals.bmpInfo.bmiHeader.biHeight = -(LONG)( Display_GetHeight( display ) );
   g_winGlobals.bmpInfo.bmiHeader.biPlanes = 1;
   g_winGlobals.bmpInfo.bmiHeader.biBitCount = 32;
   g_winGlobals.bmpInfo.bmiHeader.biCompression = BI_RGB;

   Game_Run( g_winGlobals.game );

   SaveWinDebugConfig( Clock_GetFps( Game_GetClock( g_winGlobals.game ) ) );
   
   Game_Free( g_winGlobals.game, g_winGlobals.memArena );
   MemArena_FreeMem( g_winGlobals.memArena, g_winGlobals.buttonMap );

   DeleteObject( g_winGlobals.hFont );
   DestroyWindow( g_winGlobals.hWndMain );
   UnregisterClassA( g_winGlobals.mainWindowClassName, hInstance );
   DestroyWindow( g_winGlobals.hWndDiagnostics );
   UnregisterClassA( g_winGlobals.diagnosticsWindowClassName, hInstance );
   timeEndPeriod( timerResolution );

   if ( !MemArena_IsEmpty( g_winGlobals.memArena ) )
   {
      Platform_Log( "WARNING: possible leak in memory arena, not all memory was freed on close. view the log file for details." );
      MemArena_DumpStats( g_winGlobals.memArena );
   }

   MemArena_Free( g_winGlobals.memArena );
   Platform_Log( "-----------------  EXIT  -----------------" );
   return 0;
}

void MemArena_DumpStats( MemArena_t* memArena )
{
   MemArenaStats_t stats;
   char msg[STRING_SIZE_DEFAULT];

   if ( !memArena )
   {
      Platform_Log( "mem arena stats: arena is null" );
      return;
   }

   stats = MemArena_GetStats( memArena );

   Platform_Log( "mem arena stats:" );

   snprintf( msg, STRING_SIZE_DEFAULT, "  arena size              : %zu", MemArena_GetSize( memArena ) );
   Platform_Log( msg );

   snprintf( msg, STRING_SIZE_DEFAULT, "  total allocated blocks  : %zu", stats.totalAllocatedBlocks );
   Platform_Log( msg );

   snprintf( msg, STRING_SIZE_DEFAULT, "  total allocated space   : %zu", stats.totalAllocatedSpace );
   Platform_Log( msg );

   snprintf( msg, STRING_SIZE_DEFAULT, "  largest allocated block : %zu", stats.largestAllocatedBlock );
   Platform_Log( msg );

   snprintf( msg, STRING_SIZE_DEFAULT, "  largest available block : %zu", stats.largestAvailableBlock );
   Platform_Log( msg );

   snprintf( msg, STRING_SIZE_DEFAULT, "  total unallocated space : %zu", stats.totalUnallocatedSpace );
   Platform_Log( msg );

   snprintf( msg, STRING_SIZE_DEFAULT, "  total fragments         : %zu", stats.totalFragments );
   Platform_Log( msg );

   snprintf( msg, STRING_SIZE_DEFAULT, "  total fragmented space  : %zu", stats.totalFragmentedSpace );
   Platform_Log( msg );

   snprintf( msg, STRING_SIZE_DEFAULT, "  total unusable space    : %zu", stats.totalUnusableSpace );
   Platform_Log( msg );
}

void SaveWinDebugConfig( u32 targetFps )
{
   char value[STRING_SIZE_DEFAULT];

   snprintf( value, STRING_SIZE_DEFAULT, "%u", targetFps );
   WritePrivateProfileStringA( "Windows", "TargetFps", value, g_winGlobals.debugConfigPath );

   snprintf( value, STRING_SIZE_DEFAULT, "%u", g_winDebugFlags.showDiagnostics );
   WritePrivateProfileStringA( "Windows", "ShowDiagnostics", value, g_winGlobals.debugConfigPath );

   snprintf( value, STRING_SIZE_DEFAULT, "%.1f", g_winGlobals.graphicsScale );
   WritePrivateProfileStringA( "Windows", "GraphicsScale", value, g_winGlobals.debugConfigPath );
}

internal void SetExeDir( void )
{
   char exePath[MAX_PATH];
   char msg[STRING_SIZE_DEFAULT];

   if ( !GetModuleFileNameA( NULL, exePath, MAX_PATH ) )
   {
      snprintf( msg, STRING_SIZE_DEFAULT, "failed to get executable path: %lu", GetLastError() );
      MessageBoxA( 0, msg, "Error", MB_OK | MB_ICONERROR );
      exit( 1 );
   }

   if ( !PathRemoveFileSpecA( exePath ) )
   {
      MessageBoxA( 0, "Failed to strip executable name from path", "Error", MB_OK | MB_ICONERROR );
      exit( 1 );
   }

   strcpy_s( g_winGlobals.exeDir, MAX_PATH, exePath );
}

internal void LoadWinDebugConfig( const char* filePath, u32* targetFps )
{
   char scaleText[STRING_SIZE_DEFAULT];
   r32 scale;
   u32 savedFps;
   int savedDiagnostics;

   savedFps = (u32)GetPrivateProfileIntA( "Windows", "TargetFps", (int)*targetFps, filePath );
   if ( savedFps >= MIN_GAME_FPS && savedFps <= MAX_GAME_FPS && savedFps % GAME_FPS_STEP == 0 )
   {
      *targetFps = savedFps;
   }

   savedDiagnostics = GetPrivateProfileIntA( "Windows", "ShowDiagnostics", g_winDebugFlags.showDiagnostics, filePath );
   g_winDebugFlags.showDiagnostics = savedDiagnostics == 1 ? True : False;

   GetPrivateProfileStringA( "Windows", "GraphicsScale", "", scaleText, sizeof( scaleText ), filePath );
   if ( sscanf_s( scaleText, "%f", &scale ) == 1 )
   {
      if ( scale >= MIN_GRAPHICS_SCALE && scale <= MAX_GRAPHICS_SCALE && fmodf( scale, GRAPHICS_SCALE_STEP ) == 0 )
      {
         g_winGlobals.graphicsScale = scale;
      }
   }
}

internal b32 CreateMainWindow( HINSTANCE hInstance )
{
   WNDCLASSA windowClass;
   RECT expectedWindowRect;
   DWORD windowStyle;

   strcpy_s( g_winGlobals.mainWindowClassName, MAX_PATH, "mainWindowClass" );
   windowClass.cbClsExtra = 0;
   windowClass.cbWndExtra = 0;
   windowClass.hbrBackground = 0;
   windowClass.hCursor = 0;
   windowClass.hIcon = 0;
   windowClass.lpszMenuName = 0;

   windowClass.style = CS_OWNDC | CS_HREDRAW | CS_VREDRAW;
   windowClass.lpfnWndProc = MainWindowProc;
   windowClass.hInstance = hInstance;
   windowClass.lpszClassName = g_winGlobals.mainWindowClassName;

   if ( !RegisterClassA( &windowClass ) )
   {
      return False;
   }

   expectedWindowRect.left = 0;
   expectedWindowRect.top = 0;
   expectedWindowRect.right = DISPLAY_WIDTH;
   expectedWindowRect.bottom = DISPLAY_HEIGHT;

   windowStyle = WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX | WS_VISIBLE;
   if ( !AdjustWindowRect( &expectedWindowRect, windowStyle, 0 ) )
   {
      return False;
   }

   g_winGlobals.clientPaddingRight = ( expectedWindowRect.right - expectedWindowRect.left ) - DISPLAY_WIDTH;
   g_winGlobals.clientPaddingTop = ( expectedWindowRect.bottom - expectedWindowRect.top ) - DISPLAY_HEIGHT;

   g_winGlobals.hWndMain = CreateWindowExA( 0,
                                            g_winGlobals.mainWindowClassName,
                                            STR_MAIN_WINDOW_TITLE,
                                            windowStyle,
                                            CW_USEDEFAULT,
                                            CW_USEDEFAULT,
                                            (int)( DISPLAY_WIDTH * g_winGlobals.graphicsScale ) + g_winGlobals.clientPaddingRight,
                                            (int)( DISPLAY_HEIGHT * g_winGlobals.graphicsScale ) + g_winGlobals.clientPaddingTop,
                                            0,
                                            0,
                                            hInstance,
                                            0 );

   if ( !g_winGlobals.hWndMain )
   {
      UnregisterClassA( g_winGlobals.mainWindowClassName, hInstance );
      return False;
   }

   return True;
}

internal LRESULT CALLBACK MainWindowProc( _In_ HWND hWnd, _In_ UINT uMsg, _In_ WPARAM wParam, _In_ LPARAM lParam )
{
   LRESULT result;
   RECT mainWindowRect;

   result = 0;
   switch ( uMsg )
   {
      case WM_QUIT:
      case WM_CLOSE:
      case WM_DESTROY:
         Game_Stop( g_winGlobals.game );
         break;
      case WM_MOVE:
         if ( g_winGlobals.anchorDiagnosticsWindow && g_winGlobals.hWndDiagnostics && GetWindowRect( hWnd, &mainWindowRect ) )
         {
            SetWindowPos( g_winGlobals.hWndDiagnostics,
                          NULL,
                          mainWindowRect.right + 16,
                          mainWindowRect.top,
                          0,
                          0,
                          SWP_NOSIZE | SWP_NOZORDER | SWP_NOACTIVATE );
         }
         break;
      case WM_KEYDOWN:
      case WM_KEYUP:
      case WM_SYSKEYDOWN:
      case WM_SYSKEYUP:
         HandleKeyboardInput( (u32)wParam, lParam );
         break;
      case WM_PAINT:
         RenderScreen();
         break;
      default:
         result = DefWindowProcA( hWnd, uMsg, wParam, lParam );
   }

   return result;
}

internal void RenderScreen( void )
{
   HDC dc, dcMem;
   HBITMAP bmMem;
   HANDLE hOld;
   PAINTSTRUCT ps;
   int winWidth, winHeight;
   u32 displayBufferW, displayBufferH;
   const u32* pixels;
   Display_t* display;

   display = Game_GetDisplay( g_winGlobals.game );
   winWidth = (int)( DISPLAY_WIDTH * g_winGlobals.graphicsScale );
   winHeight = (int)( DISPLAY_HEIGHT * g_winGlobals.graphicsScale );
   displayBufferW = Display_GetWidth( display );
   displayBufferH = Display_GetHeight( display );
   pixels = Display_GetPixels( display );

   dc = BeginPaint( g_winGlobals.hWndMain, &ps );

   // create an off-screen DC for double-buffering
   dcMem = CreateCompatibleDC( dc );
   bmMem = CreateCompatibleBitmap( dc, winWidth, winHeight );
   hOld = SelectObject( dcMem, bmMem );

   // actually draw everything
   StretchDIBits( dcMem,
                  0, 0, winWidth, winHeight, // dest
                  0, 0, displayBufferW, displayBufferH, // src
                  pixels,
                  &( g_winGlobals.bmpInfo ),
                  DIB_RGB_COLORS, SRCCOPY );

   // transfer the off-screen DC to the screen
   BitBlt( dc, 0, 0, winWidth, winHeight, dcMem, 0, 0, SRCCOPY );

   SelectObject( dcMem, hOld );
   DeleteObject( bmMem );
   DeleteDC( dcMem );
   EndPaint( g_winGlobals.hWndMain, &ps );
}

internal void InitButtonMap()
{
   g_winGlobals.buttonMap[InputButton_Left] = VK_LEFT;
   g_winGlobals.buttonMap[InputButton_Up] = VK_UP;
   g_winGlobals.buttonMap[InputButton_Right] = VK_RIGHT;
   g_winGlobals.buttonMap[InputButton_Down] = VK_DOWN;
   g_winGlobals.buttonMap[InputButton_A] = 0x58; // X
   g_winGlobals.buttonMap[InputButton_B] = 0x5A; // Z
   g_winGlobals.buttonMap[InputButton_Start] = VK_RETURN;
   g_winGlobals.buttonMap[InputButton_Select] = VK_SHIFT;
}

internal void HandleKeyboardInput( u32 keyCode, LPARAM flags )
{
   b32 keyWasDown, keyIsDown;
   u32 i;
   RECT mainWindowRect;
   Input_t* input;

   keyWasDown = ( flags & ( (LONG_PTR)1 << 30 ) ) != 0 ? True : False;
   keyIsDown = ( flags & ( (LONG_PTR)1 << 31 ) ) == 0 ? True : False;

   // ignore repeat presses
   if ( keyWasDown != keyIsDown )
   {
      input = Game_GetInput( g_winGlobals.game );
      
      if ( GetKeyState( VK_CONTROL ) & 0x8000 )
      {
         // ctrl should nullify all other input, so we don't end up with stuck button states
         Input_ResetAllStates( input );

         if ( keyIsDown )
         {
            if ( GetKeyState( 0x4D ) & 0x8000 ) // "M" key: dump memory stats to the log file
            {
               MemArena_DumpStats( g_winGlobals.memArena );
            }
         }
      }
      else if ( keyIsDown )
      {
         // ensure alt+F4 still closes the window
         if ( keyCode == VK_F4 && ( flags & ( (LONG_PTR)1 << 29 ) ) )
         {
            Game_Stop( g_winGlobals.game );
            return;
         }

         for ( i = 0; i < InputButton_Count; i++ )
         {
            if ( g_winGlobals.buttonMap[i] == keyCode )
            {
               Input_PressButton( input, i );
               break;
            }
         }

         switch ( keyCode )
         {
            case VK_F8:
               TOGGLE_BOOL( g_winDebugFlags.showDiagnostics );
               SaveWinDebugConfig( Clock_GetFps( Game_GetClock( g_winGlobals.game ) ) );
               if ( g_winDebugFlags.showDiagnostics )
               {
                  if ( GetWindowRect( g_winGlobals.hWndMain, &mainWindowRect ) )
                  {
                     SetWindowPos( g_winGlobals.hWndDiagnostics,
                                   HWND_TOP,
                                   mainWindowRect.right + 16,
                                   mainWindowRect.top,
                                   0,
                                   0,
                                   SWP_NOSIZE | SWP_SHOWWINDOW );
                     SetFocus( g_winGlobals.hWndMain );
                  }
                  else
                  {
                     ShowWindow( g_winGlobals.hWndDiagnostics, SW_SHOW );
                  }
               }
               else
               {
                  ShowWindow( g_winGlobals.hWndDiagnostics, SW_HIDE );
               }
               break;
         }
      }
      else
      {
         for ( i = 0; i < InputButton_Count; i++ )
         {
            if ( g_winGlobals.buttonMap[i] == keyCode )
            {
               Input_ReleaseButton( input, i );
               break;
            }
         }
      }
   }
}
