#include <shlwapi.h>
#include <stdio.h>

#include "clock.h"
#include "game.h"
#include "input.h"
#include "mem_arena.h"
#include "pixel_buffer.h"
#include "platform.h"
#include "screen.h"
#include "version.h"
#include "win_common.h"

typedef struct Popup_t
{
   b32 show;
   char msg[STRING_SIZE_DEFAULT];
   u64 untilMs;
}
Popup_t;

internal MemArena_t* CreateMemArena( void );
internal void MemArena_DumpStats( MemArena_t* memArena );
internal void SetExeDir( void );
internal void WriteTestGameDataFile( const char* filePath );
internal LRESULT CALLBACK MainWindowProc( _In_ HWND hWnd, _In_ UINT uMsg, _In_ WPARAM wParam, _In_ LPARAM lParam );
internal void RenderScreen( void );
internal void InitButtonMap( void );
internal void HandleKeyboardInput( u32 keyCode, LPARAM flags );
internal void DrawDiagnostics( HDC* dcMem );
internal void ShowPopup( const char* msg );
internal void DrawPopup( const char* msg, HDC* dcMem, int winWidth, int winHeight );
internal void DrawTranslucentRectangle( HDC hdc, int x, int y, int w, int h, COLORREF color, BYTE alpha );
internal void ResizeScreen( b32 increase );
internal void ChangeGameFps( b32 increase );

local_persist Popup_t g_popup;

WinGlobalObjects_t g_winGlobals;

int CALLBACK WinMain( _In_ HINSTANCE hInstance, _In_opt_ HINSTANCE hPrevInstance, _In_ LPSTR lpCmdLine, _In_ int nCmdShow )
{
   TIMECAPS timeCaps;
   UINT timerResolution;
   WNDCLASSA mainWindowClass;
   DWORD windowStyle;
   RECT expectedWindowRect;
   MemArena_t* memArena;
   MemArenaResult_t memArenaResult;
   char gameDataPath[MAX_PATH];

   UNUSED_PARAM( hPrevInstance );
   UNUSED_PARAM( lpCmdLine );
   UNUSED_PARAM( nCmdShow );

   SetExeDir();
   snprintf( g_winGlobals.logFilePath, MAX_PATH, "%s\\%s", g_winGlobals.exeDir, LOG_FILENAME );
   snprintf( gameDataPath, MAX_PATH, "%s\\%s", g_winGlobals.exeDir, GAME_DATA_FILENAME );

   memArena = CreateMemArena();
   memArenaResult = MemArena_Alloc( memArena, (void**)&( g_winGlobals.game ), sizeof( Game_t ) );
   if ( memArenaResult != MemArenaResult_Success )
   {
      Platform_FatalError( "failed to allocate memory for game object." );
      return 1;
   }

   memArenaResult = MemArena_Alloc( memArena, (void**)&( g_winGlobals.buttonMap ), sizeof( u32 ) * InputButton_Count );
   if ( memArenaResult != MemArenaResult_Success )
   {
      Platform_FatalError( "failed to allocate memory for button map." );
      return 1;
   }

   if ( !QueryPerformanceFrequency( &( g_winGlobals.performanceFrequency ) ) )
   {
      Platform_FatalError( "failed to query performance frequency." );
      return 1;
   }

   if ( timeGetDevCaps( &timeCaps, sizeof( TIMECAPS ) ) != TIMERR_NOERROR )
   {
      Platform_FatalError( "failed to set timer resolution." );
      return 1;
   }

   timerResolution = min( max( timeCaps.wPeriodMin, 1 ), timeCaps.wPeriodMax );
   timeBeginPeriod( timerResolution );

   // TODO: this will eventually be generated by a game editor of some kind
   WriteTestGameDataFile( gameDataPath );

   InitButtonMap();
   Game_Init( g_winGlobals.game, memArena ); // does not transfer ownership of memory arena
   Game_LoadFromFile( g_winGlobals.game, gameDataPath );

   mainWindowClass.cbClsExtra = 0;
   mainWindowClass.cbWndExtra = 0;
   mainWindowClass.hbrBackground = 0;
   mainWindowClass.hCursor = 0;
   mainWindowClass.hIcon = 0;
   mainWindowClass.lpszMenuName = 0;

   mainWindowClass.style = CS_OWNDC | CS_HREDRAW | CS_VREDRAW;
   mainWindowClass.lpfnWndProc = MainWindowProc;
   mainWindowClass.hInstance = hInstance;
   mainWindowClass.lpszClassName = "mainWindowClass";

   if ( !RegisterClassA( &mainWindowClass ) )
   {
      Platform_FatalError( "failed to register window class." );
      return 1;
   }

   expectedWindowRect.left = 0;
   expectedWindowRect.top = 0;
   expectedWindowRect.right = SCREEN_WIDTH;
   expectedWindowRect.bottom = SCREEN_HEIGHT;

   windowStyle = WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX | WS_VISIBLE;
   if ( !AdjustWindowRect( &expectedWindowRect, windowStyle, 0 ) )
   {
      Platform_FatalError( "failed to adjust window rect." );
      return 1;
   }

   g_winGlobals.clientPaddingRight = ( expectedWindowRect.right - expectedWindowRect.left ) - SCREEN_WIDTH;
   g_winGlobals.clientPaddingTop = ( expectedWindowRect.bottom - expectedWindowRect.top ) - SCREEN_HEIGHT;

   g_winGlobals.graphicsScale = DEFAULT_GRAPHICS_SCALE;
   g_winGlobals.showDiagnostics = False;

   // TODO: put the window title somewhere else
   g_winGlobals.hWndMain = CreateWindowExA( 0,
                                            mainWindowClass.lpszClassName,
                                            "Dragon Quest 3",
                                            windowStyle,
                                            CW_USEDEFAULT,
                                            CW_USEDEFAULT,
                                            (int)( SCREEN_WIDTH * g_winGlobals.graphicsScale ) + g_winGlobals.clientPaddingRight,
                                            (int)( SCREEN_HEIGHT * g_winGlobals.graphicsScale ) + g_winGlobals.clientPaddingTop,
                                            0,
                                            0,
                                            hInstance,
                                            0 );

   if ( !g_winGlobals.hWndMain )
   {
      Platform_FatalError( "failed to create main window." );
      return 1;
   }

   SetCursor( LoadCursor( 0, IDC_ARROW ) );

   g_winGlobals.hFont = CreateFontA( 16, 0, 0, 0,
                                     FW_BOLD, FALSE, FALSE, FALSE,
                                     ANSI_CHARSET, OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS,
                                     DEFAULT_QUALITY, DEFAULT_PITCH | FF_SWISS,
                                     "Consolas" );

   g_winGlobals.bmpInfo.bmiHeader.biSize = sizeof( BITMAPINFOHEADER );
   g_winGlobals.bmpInfo.bmiHeader.biWidth = g_winGlobals.game->screen->buffer->w;
   g_winGlobals.bmpInfo.bmiHeader.biHeight = -(LONG)( g_winGlobals.game->screen->buffer->h );
   g_winGlobals.bmpInfo.bmiHeader.biPlanes = 1;
   g_winGlobals.bmpInfo.bmiHeader.biBitCount = 32;
   g_winGlobals.bmpInfo.bmiHeader.biCompression = BI_RGB;

   Game_Run( g_winGlobals.game );

   MemArena_Destroy( &( memArena ) );
   return 0;
}

internal MemArena_t* CreateMemArena( void )
{
   MemArenaResult_t result;
   char msg[STRING_SIZE_DEFAULT];
   MemArena_t* memArena;

   memArena = 0;
   result = MemArena_Create( &( memArena ), GAME_MEMORY_SIZE );
   if ( result != MemArenaResult_Success )
   {
      snprintf( msg, STRING_SIZE_DEFAULT, "failed to create memory arena for game object: %s", MemArena_GetErrorMessage( result ) );
      Platform_FatalError( msg );
   }

   return memArena;
}

internal void MemArena_DumpStats( MemArena_t* memArena )
{
   MemArenaStats_t stats;
   char msg[STRING_SIZE_DEFAULT];

   if ( !memArena )
   {
      Platform_Log( "mem arena stats: arena is null" );
      return;
   }

   stats = MemArena_GetStats( memArena );

   Platform_Log( "mem arena stats:" );

   snprintf( msg, STRING_SIZE_DEFAULT, "  arena size              : %zu", memArena->size );
   Platform_Log( msg );

   snprintf( msg, STRING_SIZE_DEFAULT, "  largest available block : %zu", stats.largestAvailableBlock );
   Platform_Log( msg );

   snprintf( msg, STRING_SIZE_DEFAULT, "  total allocated space   : %zu", stats.totalAllocatedSpace );
   Platform_Log( msg );

   snprintf( msg, STRING_SIZE_DEFAULT, "  total unallocated space : %zu", stats.totalUnallocatedSpace );
   Platform_Log( msg );

   snprintf( msg, STRING_SIZE_DEFAULT, "  total fragmented space  : %zu", stats.totalFragmentedSpace );
   Platform_Log( msg );

   snprintf( msg, STRING_SIZE_DEFAULT, "  total unusable space    : %zu", stats.totalUnusableSpace );
   Platform_Log( msg );
}

internal void SetExeDir( void )
{
   char exePath[MAX_PATH];
   char msg[STRING_SIZE_DEFAULT];

   if ( !GetModuleFileNameA( NULL, exePath, MAX_PATH ) )
   {
      snprintf( msg, STRING_SIZE_DEFAULT, "failed to get executable path: %lu", GetLastError() );
      MessageBoxA( 0, msg, "Error", MB_OK | MB_ICONERROR );
      exit( 1 );
   }

   if ( !PathRemoveFileSpecA( exePath ) )
   {
      MessageBoxA( 0, "Failed to strip executable name from path", "Error", MB_OK | MB_ICONERROR );
      exit( 1 );
   }

   strcpy_s( g_winGlobals.exeDir, MAX_PATH, exePath );
}

// TODO: we can get rid of this once we have a proper game editor
internal void WriteTestGameDataFile( const char* filePath )
{
   HANDLE hFile;
   DWORD bytesWritten;
   BOOL result;
   GameDataHeader_t header;
   u32 i;
   char msg[STRING_SIZE_DEFAULT];

   hFile = CreateFileA( filePath, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL );

   if ( hFile == INVALID_HANDLE_VALUE )
   {
      snprintf( msg, STRING_SIZE_DEFAULT, "failed to write test game data file: %lu", GetLastError() );
      Platform_FatalError( msg );
   }

   for ( i = 0; i < 4; i++ )
   {
      header.magic[i] = GAME_DATA_MAGIC[i];
   }
   header.version.major = GAME_VERSION_MAJOR;
   header.version.minor = GAME_VERSION_MINOR;
   header.version.maint = GAME_VERSION_MAINT;;

   bytesWritten = 0;
   result = WriteFile( hFile, &header, sizeof( GameDataHeader_t ), &bytesWritten, NULL );

   if ( !result )
   {
      snprintf( msg, STRING_SIZE_DEFAULT, "failed to write test game data file: %lu", GetLastError() );
      Platform_FatalError( msg );
   }
   else if ( bytesWritten != sizeof( GameDataHeader_t ) )
   {
      snprintf( msg, STRING_SIZE_DEFAULT, "failed to write test game data file: wrote %lu of %lu bytes", bytesWritten, sizeof( GameDataHeader_t ) );
      Platform_FatalError( msg );
   }

   CloseHandle( hFile );
}

internal LRESULT CALLBACK MainWindowProc( _In_ HWND hWnd, _In_ UINT uMsg, _In_ WPARAM wParam, _In_ LPARAM lParam )
{
   LRESULT result = 0;

   switch ( uMsg )
   {
      case WM_QUIT:
      case WM_CLOSE:
      case WM_DESTROY:
         Game_Stop( g_winGlobals.game );
         break;
      case WM_KEYDOWN:
      case WM_KEYUP:
      case WM_SYSKEYDOWN:
      case WM_SYSKEYUP:
         HandleKeyboardInput( (u32)wParam, lParam );
         break;
      case WM_PAINT:
         RenderScreen();
         break;
      default:
         result = DefWindowProcA( hWnd, uMsg, wParam, lParam );
   }

   return result;
}

// the double-buffering part of this came from Stack Overflow
internal void RenderScreen( void )
{
   HDC dc, dcMem;
   HBITMAP bmMem;
   HANDLE hOld;
   PAINTSTRUCT ps;
   int winWidth, winHeight;

   winWidth = (int)( SCREEN_WIDTH * g_winGlobals.graphicsScale );
   winHeight = (int)( SCREEN_HEIGHT * g_winGlobals.graphicsScale );

   dc = BeginPaint( g_winGlobals.hWndMain, &ps );

   // create an off-screen DC for double-buffering
   dcMem = CreateCompatibleDC( dc );
   bmMem = CreateCompatibleBitmap( dc, winWidth, winHeight );
   hOld = SelectObject( dcMem, bmMem );

   // actually draw everything
   StretchDIBits( dcMem,
                  0, 0, winWidth, winHeight, // dest
                  0, 0, g_winGlobals.game->screen->buffer->w, g_winGlobals.game->screen->buffer->h, // src
                  g_winGlobals.game->screen->buffer->mem,
                  &( g_winGlobals.bmpInfo ),
                  DIB_RGB_COLORS, SRCCOPY );

   if ( g_winGlobals.showDiagnostics )
   {
      DrawDiagnostics( &dcMem );
   }

   if ( g_popup.show )
   {
      DrawPopup( g_popup.msg, &dcMem, winWidth, winHeight );
   }

   // transfer the off-screen DC to the screen
   BitBlt( dc, 0, 0, winWidth, winHeight, dcMem, 0, 0, SRCCOPY );

   SelectObject( dcMem, hOld );
   DeleteObject( bmMem );
   DeleteDC( dcMem );
   EndPaint( g_winGlobals.hWndMain, &ps );
}

internal void InitButtonMap()
{
   g_winGlobals.buttonMap[InputButton_Left] = VK_LEFT;
   g_winGlobals.buttonMap[InputButton_Up] = VK_UP;
   g_winGlobals.buttonMap[InputButton_Right] = VK_RIGHT;
   g_winGlobals.buttonMap[InputButton_Down] = VK_DOWN;
   g_winGlobals.buttonMap[InputButton_A] = 0x58; // X
   g_winGlobals.buttonMap[InputButton_B] = 0x5A; // Z
   g_winGlobals.buttonMap[InputButton_Start] = VK_RETURN;
   g_winGlobals.buttonMap[InputButton_Select] = VK_SHIFT;
}

internal void HandleKeyboardInput( u32 keyCode, LPARAM flags )
{
   b32 keyWasDown, keyIsDown;
   u32 i;

   keyWasDown = ( flags & ( (LONG_PTR)1 << 30 ) ) != 0 ? True : False;
   keyIsDown = ( flags & ( (LONG_PTR)1 << 31 ) ) == 0 ? True : False;

   // ignore repeat presses
   if ( keyWasDown != keyIsDown )
   {
      if ( GetKeyState( VK_CONTROL ) & 0x8000 )
      {
         // ctrl should nullify all other input, so we don't end up with stuck button states
         Input_ResetAllStates( g_winGlobals.game->input );

         if ( keyIsDown )
         {
            if ( GetKeyState( 0x53 ) & 0x8000 ) // "S" key: change the scale of the screen
            {
               switch ( keyCode )
               {
                  case VK_UP:
                     ResizeScreen( True );
                     break;
                  case VK_DOWN:
                     ResizeScreen( False );
                     break;
               }
            }
            else if ( GetKeyState( 0x46 ) & 0x8000 ) // "F" key: change the game's frame rate
            {
               switch ( keyCode )
               {
                  case VK_UP:
                     ChangeGameFps( True );
                     break;
                  case VK_DOWN:
                     ChangeGameFps( False );
                     break;
               }
            }
            else if ( GetKeyState( 0x4D ) & 0x8000 ) // "M" key: dump memory stats to the log file
            {
               MemArena_DumpStats( g_winGlobals.game->memArena );
               ShowPopup( "Memory stats dumped to log" );
            }
         }
      }

      else if ( keyIsDown )
      {
         // ensure alt+F4 still closes the window
         if ( keyCode == VK_F4 && ( flags & ( (LONG_PTR)1 << 29 ) ) )
         {
            Game_Stop( g_winGlobals.game );
            return;
         }

         for ( i = 0; i < InputButton_Count; i++ )
         {
            if ( g_winGlobals.buttonMap[i] == keyCode )
            {
               Input_PressButton( g_winGlobals.game->input, i );
               break;
            }
         }

         switch ( keyCode )
         {
            case VK_F8:
               TOGGLE_BOOL( g_winGlobals.showDiagnostics );
               break;
         }
      }
      else
      {
         for ( i = 0; i < InputButton_Count; i++ )
         {
            if ( g_winGlobals.buttonMap[i] == keyCode )
            {
               Input_ReleaseButton( g_winGlobals.game->input, i );
               break;
            }
         }
      }
   }
}

internal void DrawDiagnostics( HDC* dcMem )
{
   u32 gameSeconds, realSeconds;
   RECT r;
   HFONT oldFont;
   Game_t* game;
   char str[STRING_SIZE_DEFAULT];

   game = g_winGlobals.game;

   r.left = 10;
   r.top = 10;
   r.right = 0;
   r.bottom = 0;

   // backdrop
   DrawTranslucentRectangle( *dcMem, 0, 0, 256, 206, RGB( 0, 0, 128 ), 200 );

   oldFont = (HFONT)SelectObject( *dcMem, g_winGlobals.hFont );

   SetTextColor( *dcMem, 0x00FFFFFF );
   SetBkMode( *dcMem, TRANSPARENT );

   sprintf_s( str, STRING_SIZE_DEFAULT, "Target Frame Rate: %u", game->clock->fps );
   DrawTextA( *dcMem, str, -1, &r, DT_SINGLELINE | DT_NOCLIP );
   r.top += 16;

   sprintf_s( str, STRING_SIZE_DEFAULT, "    Last Frame MS: %u", (u32)( game->clock->lastframeMicro / 1000 ) );
   DrawTextA( *dcMem, str, -1, &r, DT_SINGLELINE | DT_NOCLIP );
   r.top += 16;

   sprintf_s( str, STRING_SIZE_DEFAULT, "     Total Frames: %u", game->clock->frameCount );
   DrawTextA( *dcMem, str, -1, &r, DT_SINGLELINE | DT_NOCLIP );
   r.top += 16;

   sprintf_s( str, STRING_SIZE_DEFAULT, "       Lag Frames: %u", game->clock->lagFrameCount );
   DrawTextA( *dcMem, str, -1, &r, DT_SINGLELINE | DT_NOCLIP );
   r.top += 16;

   sprintf_s( str, STRING_SIZE_DEFAULT, "   Graphics Scale: %.1f", g_winGlobals.graphicsScale );
   DrawTextA( *dcMem, str, -1, &r, DT_SINGLELINE | DT_NOCLIP );
   r.top += 16;

   gameSeconds = game->clock->frameCount / game->clock->fps;
   sprintf_s( str, STRING_SIZE_DEFAULT, "    In-Game Timer: %u:%02u:%02u", gameSeconds / 3600, gameSeconds / 60, gameSeconds );
   DrawTextA( *dcMem, str, -1, &r, DT_SINGLELINE | DT_NOCLIP );
   r.top += 16;

   realSeconds = (u32)( game->clock->absoluteEndMicro - game->clock->absoluteStartMicro ) / 1000000;
   sprintf_s( str, STRING_SIZE_DEFAULT, " Real World Timer: %u:%02u:%02u", realSeconds / 3600, realSeconds / 60, realSeconds );
   DrawTextA( *dcMem, str, -1, &r, DT_SINGLELINE | DT_NOCLIP );
   r.top += 16;

   r.top += 16;

   sprintf_s( str, STRING_SIZE_DEFAULT, "  |" );
   SetTextColor( *dcMem, game->input->buttonStates[InputButton_Up].down ? 0x00FFFFFF : 0x00777777 );
   DrawTextA( *dcMem, str, -1, &r, DT_SINGLELINE | DT_NOCLIP );
   r.top += 16;

   sprintf_s( str, STRING_SIZE_DEFAULT, "--" );
   SetTextColor( *dcMem, game->input->buttonStates[InputButton_Left].down ? 0x00FFFFFF : 0x00777777 );
   DrawTextA( *dcMem, str, -1, &r, DT_SINGLELINE | DT_NOCLIP );

   sprintf_s( str, STRING_SIZE_DEFAULT, "   --" );
   SetTextColor( *dcMem, game->input->buttonStates[InputButton_Right].down ? 0x00FFFFFF : 0x00777777 );
   DrawTextA( *dcMem, str, -1, &r, DT_SINGLELINE | DT_NOCLIP );

   sprintf_s( str, STRING_SIZE_DEFAULT, "      SEL" );
   SetTextColor( *dcMem, game->input->buttonStates[InputButton_Select].down ? 0x00FFFFFF : 0x00777777 );
   DrawTextA( *dcMem, str, -1, &r, DT_SINGLELINE | DT_NOCLIP );

   sprintf_s( str, STRING_SIZE_DEFAULT, "          STA" );
   SetTextColor( *dcMem, game->input->buttonStates[InputButton_Start].down ? 0x00FFFFFF : 0x00777777 );
   DrawTextA( *dcMem, str, -1, &r, DT_SINGLELINE | DT_NOCLIP );

   sprintf_s( str, STRING_SIZE_DEFAULT, "              B" );
   SetTextColor( *dcMem, game->input->buttonStates[InputButton_B].down ? 0x00FFFFFF : 0x00777777 );
   DrawTextA( *dcMem, str, -1, &r, DT_SINGLELINE | DT_NOCLIP );

   sprintf_s( str, STRING_SIZE_DEFAULT, "                A" );
   SetTextColor( *dcMem, game->input->buttonStates[InputButton_A].down ? 0x00FFFFFF : 0x00777777 );
   DrawTextA( *dcMem, str, -1, &r, DT_SINGLELINE | DT_NOCLIP );
   r.top += 16;

   sprintf_s( str, STRING_SIZE_DEFAULT, "  |" );
   SetTextColor( *dcMem, game->input->buttonStates[InputButton_Down].down ? 0x00FFFFFF : 0x00777777 );
   DrawTextA( *dcMem, str, -1, &r, DT_SINGLELINE | DT_NOCLIP );
   r.top += 16;

   SelectObject( *dcMem, oldFont );
}

internal void ShowPopup( const char* msg )
{
   g_popup.show = True;
   strncpy_s( g_popup.msg, STRING_SIZE_DEFAULT, msg, STRING_SIZE_DEFAULT - 1 );
   g_popup.untilMs = GetTickCount64() + 3000;
}

internal void DrawPopup( const char* msg, HDC* dcMem, int winWidth, int winHeight )
{
   RECT r;
   SIZE textSize;
   HFONT oldFont;
   int boxWidth, boxHeight, boxX, boxY;

   if ( GetTickCount64() > g_popup.untilMs )
   {
      g_popup.show = False;
      return;
   }

   oldFont = (HFONT)SelectObject( *dcMem, g_winGlobals.hFont );

   if ( !GetTextExtentPoint32A( *dcMem, msg, lstrlenA( msg ), &textSize ) )
   {
      textSize.cx = 320;
      textSize.cy = 16;
   }

   boxWidth = textSize.cx + 20;
   if ( boxWidth < 120 )
   {
      boxWidth = 120;
   }

   boxHeight = textSize.cy + 12;
   boxX = winWidth - boxWidth - 12;
   boxY = winHeight - boxHeight - 12;

   DrawTranslucentRectangle( *dcMem, boxX, boxY, boxWidth, boxHeight, RGB( 0, 128, 0 ), 210 );

   r.left = boxX + 10;
   r.top = boxY + 6;
   r.right = boxX + boxWidth;
   r.bottom = boxY + boxHeight;

   SetTextColor( *dcMem, 0x00FFFFFF );
   SetBkMode( *dcMem, TRANSPARENT );
   DrawTextA( *dcMem, msg, -1, &r, DT_SINGLELINE | DT_NOCLIP );
   SelectObject( *dcMem, oldFont );
}

internal void DrawTranslucentRectangle( HDC hdc, int x, int y, int w, int h, COLORREF color, BYTE alpha )
{
   HDC hdcMem = CreateCompatibleDC( hdc );
   HBITMAP bitmap = CreateCompatibleBitmap( hdc, w, h );
   HBITMAP oldBitmap = (HBITMAP)SelectObject( hdcMem, bitmap );

   HBRUSH blueBrush = CreateSolidBrush( color );
   HBRUSH oldBrush = (HBRUSH)SelectObject( hdcMem, blueBrush );

   Rectangle( hdcMem, 0, 0, w, h );

   BLENDFUNCTION bf;
   bf.BlendOp = AC_SRC_OVER;
   bf.BlendFlags = 0;
   bf.SourceConstantAlpha = alpha;
   bf.AlphaFormat = 0;

   AlphaBlend( hdc, x, y, w, h, hdcMem, 0, 0, w, h, bf );

   SelectObject( hdcMem, oldBrush );
   DeleteObject( blueBrush );
   SelectObject( hdcMem, oldBitmap );
   DeleteObject( bitmap );
   DeleteDC( hdcMem );
}

internal void ResizeScreen( b32 increase )
{
   b32 changed;

   changed = False;
   if ( increase && g_winGlobals.graphicsScale < MAX_GRAPHICS_SCALE )
   {
      g_winGlobals.graphicsScale += GRAPHICS_SCALE_STEP;
      changed = True;
   }
   else if ( !increase && g_winGlobals.graphicsScale > MIN_GRAPHICS_SCALE )
   {
      g_winGlobals.graphicsScale -= GRAPHICS_SCALE_STEP;
      changed = True;
   }

   if ( changed )
   {
      SetWindowPos( g_winGlobals.hWndMain,
                    NULL, // No change in Z-order
                    0, 0, // No change in position
                    (int)( SCREEN_WIDTH * g_winGlobals.graphicsScale ) + g_winGlobals.clientPaddingRight, 
                    (int)( SCREEN_HEIGHT * g_winGlobals.graphicsScale ) + g_winGlobals.clientPaddingTop,
                    SWP_NOMOVE | SWP_NOZORDER | SWP_ASYNCWINDOWPOS); 
   }
}

internal void ChangeGameFps( b32 increase )
{
   if ( increase && g_winGlobals.game->clock->fps < MAX_GAME_FPS )
   {
      Clock_SetFps( g_winGlobals.game->clock, g_winGlobals.game->clock->fps + GAME_FPS_STEP );
   }
   else if ( !increase && g_winGlobals.game->clock->fps > MIN_GAME_FPS )
   {
      Clock_SetFps( g_winGlobals.game->clock, g_winGlobals.game->clock->fps - GAME_FPS_STEP );
   }
}
